/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "KnowledgeBaseS3DataSource": {
      "id": string
      "type": "aws.bedrock/agentDataSource.AgentDataSource"
    }
    "KnowledgeBaseSyncFunction": {
      "name": string
      "type": "sst.aws.Function"
    }
    "ModelInfo": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "MyApi": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "MyBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "MyWeb": {
      "type": "sst.aws.StaticSite"
      "url": string
    }
    "NewCustomers": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "OldCustomers": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "Rds": {
      "clusterArn": string
      "database": string
      "host": string
      "password": string
      "port": number
      "reader": string
      "secretArn": string
      "type": "sst.aws.Aurora"
      "username": string
    }
    "TicketCreationFunction": {
      "name": string
      "type": "sst.aws.Function"
    }
    "Tickets": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "Vpc": {
      "bastion": string
      "type": "sst.aws.Vpc"
    }
    "agent-for-ticket-creation-v1-Pulumi": {
      "agentId": string
      "type": "aws.bedrock/agentAgent.AgentAgent"
    }
    "knowledgeBase": {
      "arn": string
      "id": string
      "type": "aws.bedrock/agentKnowledgeBase.AgentKnowledgeBase"
    }
    "ticket-agent-alias": {
      "agentAliasArn": string
      "agentAliasId": string
      "agentId": string
      "type": "aws.bedrock/agentAgentAlias.AgentAgentAlias"
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}