/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { CreateFileRoute, FileRoutesByPath } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as TicketsRouteImport } from './routes/tickets'
import { Route as ModelSelectorRouteImport } from './routes/model-selector'
import { Route as KnowledgeBaseRouteImport } from './routes/knowledge-base'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgentsIndexRouteImport } from './routes/agents.index'
import { Route as AgentsAgentIdRouteImport } from './routes/agents.$agentId'

const TicketsRoute = TicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelSelectorRoute = ModelSelectorRouteImport.update({
  id: '/model-selector',
  path: '/model-selector',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeBaseRoute = KnowledgeBaseRouteImport.update({
  id: '/knowledge-base',
  path: '/knowledge-base',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsIndexRoute = AgentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AgentsRoute,
} as any)
const AgentsAgentIdRoute = AgentsAgentIdRouteImport.update({
  id: '/$agentId',
  path: '/$agentId',
  getParentRoute: () => AgentsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRouteWithChildren
  '/customers': typeof CustomersRoute
  '/knowledge-base': typeof KnowledgeBaseRoute
  '/model-selector': typeof ModelSelectorRoute
  '/tickets': typeof TicketsRoute
  '/agents/$agentId': typeof AgentsAgentIdRoute
  '/agents/': typeof AgentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/customers': typeof CustomersRoute
  '/knowledge-base': typeof KnowledgeBaseRoute
  '/model-selector': typeof ModelSelectorRoute
  '/tickets': typeof TicketsRoute
  '/agents/$agentId': typeof AgentsAgentIdRoute
  '/agents': typeof AgentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agents': typeof AgentsRouteWithChildren
  '/customers': typeof CustomersRoute
  '/knowledge-base': typeof KnowledgeBaseRoute
  '/model-selector': typeof ModelSelectorRoute
  '/tickets': typeof TicketsRoute
  '/agents/$agentId': typeof AgentsAgentIdRoute
  '/agents/': typeof AgentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agents'
    | '/customers'
    | '/knowledge-base'
    | '/model-selector'
    | '/tickets'
    | '/agents/$agentId'
    | '/agents/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/customers'
    | '/knowledge-base'
    | '/model-selector'
    | '/tickets'
    | '/agents/$agentId'
    | '/agents'
  id:
    | '__root__'
    | '/'
    | '/agents'
    | '/customers'
    | '/knowledge-base'
    | '/model-selector'
    | '/tickets'
    | '/agents/$agentId'
    | '/agents/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentsRoute: typeof AgentsRouteWithChildren
  CustomersRoute: typeof CustomersRoute
  KnowledgeBaseRoute: typeof KnowledgeBaseRoute
  ModelSelectorRoute: typeof ModelSelectorRoute
  TicketsRoute: typeof TicketsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge-base': {
      id: '/knowledge-base'
      path: '/knowledge-base'
      fullPath: '/knowledge-base'
      preLoaderRoute: typeof KnowledgeBaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/model-selector': {
      id: '/model-selector'
      path: '/model-selector'
      fullPath: '/model-selector'
      preLoaderRoute: typeof ModelSelectorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tickets': {
      id: '/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof TicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/$agentId': {
      id: '/agents/$agentId'
      path: '/$agentId'
      fullPath: '/agents/$agentId'
      preLoaderRoute: typeof AgentsAgentIdRouteImport
      parentRoute: typeof AgentsRoute
    }
    '/agents/': {
      id: '/agents/'
      path: '/'
      fullPath: '/agents/'
      preLoaderRoute: typeof AgentsIndexRouteImport
      parentRoute: typeof AgentsRoute
    }
  }
}

declare module './routes/index' {
  const createFileRoute: CreateFileRoute<
    '/',
    FileRoutesByPath['/']['parentRoute'],
    FileRoutesByPath['/']['id'],
    FileRoutesByPath['/']['path'],
    FileRoutesByPath['/']['fullPath']
  >
}
declare module './routes/agents' {
  const createFileRoute: CreateFileRoute<
    '/agents',
    FileRoutesByPath['/agents']['parentRoute'],
    FileRoutesByPath['/agents']['id'],
    FileRoutesByPath['/agents']['path'],
    FileRoutesByPath['/agents']['fullPath']
  >
}
declare module './routes/customers' {
  const createFileRoute: CreateFileRoute<
    '/customers',
    FileRoutesByPath['/customers']['parentRoute'],
    FileRoutesByPath['/customers']['id'],
    FileRoutesByPath['/customers']['path'],
    FileRoutesByPath['/customers']['fullPath']
  >
}
declare module './routes/knowledge-base' {
  const createFileRoute: CreateFileRoute<
    '/knowledge-base',
    FileRoutesByPath['/knowledge-base']['parentRoute'],
    FileRoutesByPath['/knowledge-base']['id'],
    FileRoutesByPath['/knowledge-base']['path'],
    FileRoutesByPath['/knowledge-base']['fullPath']
  >
}
declare module './routes/model-selector' {
  const createFileRoute: CreateFileRoute<
    '/model-selector',
    FileRoutesByPath['/model-selector']['parentRoute'],
    FileRoutesByPath['/model-selector']['id'],
    FileRoutesByPath['/model-selector']['path'],
    FileRoutesByPath['/model-selector']['fullPath']
  >
}
declare module './routes/tickets' {
  const createFileRoute: CreateFileRoute<
    '/tickets',
    FileRoutesByPath['/tickets']['parentRoute'],
    FileRoutesByPath['/tickets']['id'],
    FileRoutesByPath['/tickets']['path'],
    FileRoutesByPath['/tickets']['fullPath']
  >
}
declare module './routes/agents.$agentId' {
  const createFileRoute: CreateFileRoute<
    '/agents/$agentId',
    FileRoutesByPath['/agents/$agentId']['parentRoute'],
    FileRoutesByPath['/agents/$agentId']['id'],
    FileRoutesByPath['/agents/$agentId']['path'],
    FileRoutesByPath['/agents/$agentId']['fullPath']
  >
}
declare module './routes/agents.index' {
  const createFileRoute: CreateFileRoute<
    '/agents/',
    FileRoutesByPath['/agents/']['parentRoute'],
    FileRoutesByPath['/agents/']['id'],
    FileRoutesByPath['/agents/']['path'],
    FileRoutesByPath['/agents/']['fullPath']
  >
}

interface AgentsRouteChildren {
  AgentsAgentIdRoute: typeof AgentsAgentIdRoute
  AgentsIndexRoute: typeof AgentsIndexRoute
}

const AgentsRouteChildren: AgentsRouteChildren = {
  AgentsAgentIdRoute: AgentsAgentIdRoute,
  AgentsIndexRoute: AgentsIndexRoute,
}

const AgentsRouteWithChildren =
  AgentsRoute._addFileChildren(AgentsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentsRoute: AgentsRouteWithChildren,
  CustomersRoute: CustomersRoute,
  KnowledgeBaseRoute: KnowledgeBaseRoute,
  ModelSelectorRoute: ModelSelectorRoute,
  TicketsRoute: TicketsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
